# Generated by Django 5.2.15 on 2026-06-28 00:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitlistUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('forget_type', models.CharField(choices=[('keys', 'Keys / wallet / phone'), ('tasks', 'Tasks and deadlines'), ('events', 'Events and birthdays'), ('objects', 'Where I put things'), ('other', 'Everything honestly')], max_length=20)),
                ('referral_code', models.CharField(max_length=12, unique=True)),
                ('referred_by', models.CharField(blank=True, max_length=12, null=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('lifestyle', models.CharField(choices=[('student', 'Student'), ('professional', 'Working Professional'), ('parent', 'Parent / Caregiver'), ('other', 'Other')], default='other', max_length=20)),
                ('forget_type', models.CharField(choices=[('keys', 'Keys / wallet / phone'), ('tasks', 'Tasks and deadlines'), ('events', 'Events and birthdays'), ('objects', 'Where I put things'), ('other', 'Everything honestly')], default='other', max_length=20)),
                ('totp_secret', models.CharField(blank=True, max_length=64)),
                ('is_2fa_enabled', models.BooleanField(default=False)),
                ('is_2fa_verified', models.BooleanField(default=False)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('email_verify_token', models.CharField(blank=True, max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('referral_code', models.CharField(blank=True, max_length=12, unique=True)),
                ('referred_by', models.CharField(blank=True, max_length=12, null=True)),
                ('referral_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('raw_text', models.TextField()),
                ('input_mode', models.CharField(choices=[('text', 'Text'), ('voice', 'Voice')], default='text', max_length=10)),
                ('parsed_what', models.CharField(blank=True, max_length=400)),
                ('parsed_when', models.DateTimeField(blank=True, null=True)),
                ('parsed_where', models.CharField(blank=True, max_length=400)),
                ('category', models.CharField(choices=[('task', 'Task'), ('event', 'Event'), ('object', 'Object / location'), ('reminder', 'Reminder'), ('query', 'Query'), ('other', 'Other')], default='other', max_length=20)),
                ('importance', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3)),
                ('ai_response', models.TextField(blank=True)),
                ('is_done', models.BooleanField(default=False)),
                ('reminded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
