# Generated by Django 5.2.15 on 2026-06-22 06:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_email', models.EmailField(max_length=254)),
                ('raw_text', models.TextField()),
                ('parsed_what', models.CharField(blank=True, max_length=300)),
                ('parsed_when', models.DateTimeField(blank=True, null=True)),
                ('parsed_where', models.CharField(blank=True, max_length=300)),
                ('category', models.CharField(choices=[('task', 'Task'), ('event', 'Event'), ('object', 'Object / location'), ('reminder', 'Reminder'), ('other', 'Other')], default='other', max_length=20)),
                ('importance', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3)),
                ('is_done', models.BooleanField(default=False)),
                ('reminded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WaitlistUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('forget_type', models.CharField(choices=[('keys', 'Keys / wallet / phone'), ('tasks', 'Tasks and deadlines'), ('events', 'Events and birthdays'), ('objects', 'Where I put things'), ('other', 'Everything honestly')], max_length=20)),
                ('referral_code', models.CharField(max_length=12, unique=True)),
                ('referred_by', models.CharField(blank=True, max_length=12, null=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
